const express = require("express");
const cors = require("cors");
const PDFDocument = require("pdfkit");

const app = express();
app.use(cors());
app.use(express.json());

app.get("/", (req, res) => {
  res.send("API RUNNING - FREE PDF GENERATOR");
});

app.post("/api/generate-pdf", async (req, res) => {
  try {
    const { title, text } = req.body;

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", "inline; filename=generated.pdf");

    const doc = new PDFDocument({ size: "A4", margin: 50 });

    // 🔥 IMPORTANT
    doc.pipe(res);

    // ===== PDF DESIGN (PREMIUM BASIC) =====
    doc
      .fontSize(22)
      .text(title || "PDF Generator", { align: "center" });

    doc.moveDown(2);

    doc
      .fontSize(12)
      .text(text || "No content provided", {
        align: "left",
        lineGap: 6,
      });

    doc.moveDown(3);

    doc
      .fontSize(10)
      .fillColor("gray")
      .text("Generated by Free PDF API", { align: "center" });

    doc.end(); // ❗ MUST
  } catch (err) {
    console.error(err);
    res.status(500).send("PDF generation failed");
  }
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log("Server started on " + PORT));